-- HeyBeauty: production schema and sample data.
-- Apply this once in Supabase Dashboard > SQL Editor.

create extension if not exists pgcrypto;

create type public.app_role as enum ('customer', 'clinic_admin');
create type public.appointment_status as enum ('상담대기', '예약확정', '방문완료', '취소');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.app_role not null default 'customer',
  name text,
  phone text,
  created_at timestamptz not null default now()
);

create table public.clinics (
  id bigint generated by default as identity primary key,
  name text not null,
  district text not null,
  rating numeric(2,1) not null check (rating between 0 and 5),
  description text not null,
  admin_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.services (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id) on delete cascade,
  name text not null,
  category text not null,
  price integer not null check (price >= 0),
  duration text not null,
  slots text[] not null default '{}',
  is_active boolean not null default true
);

create table public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  name text not null,
  phone text,
  concern text,
  preferred_service text,
  notes text,
  created_at timestamptz not null default now()
);

create table public.chat_profiles (
  user_id text primary key,
  name text,
  phone text,
  concern text,
  preferred_service text,
  updated_at timestamptz not null default now()
);

create table public.appointments (
  id bigint generated by default as identity primary key,
  clinic_id bigint not null references public.clinics(id),
  service_id bigint not null references public.services(id),
  customer_id bigint not null references public.customers(id),
  slot timestamptz not null,
  status public.appointment_status not null default '상담대기',
  source text not null default 'HeyBeauty 채팅',
  created_at timestamptz not null default now()
);

create index appointments_clinic_slot_idx on public.appointments(clinic_id, slot);
create index services_clinic_idx on public.services(clinic_id);
create index customers_user_idx on public.customers(user_id);

alter table public.profiles enable row level security;
alter table public.clinics enable row level security;
alter table public.services enable row level security;
alter table public.customers enable row level security;
alter table public.chat_profiles enable row level security;
alter table public.appointments enable row level security;

-- Public visitors can browse clinics and active services only.
create policy "public can read clinics" on public.clinics for select using (true);
create policy "public can read active services" on public.services for select using (is_active = true);

-- Logged-in users can access only their profile and customer records.
create policy "users view own profile" on public.profiles for select to authenticated using (id = (select auth.uid()));
create policy "users update own profile" on public.profiles for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));
create policy "users view own customer records" on public.customers for select to authenticated using (user_id = (select auth.uid()));
create policy "users view own appointments" on public.appointments for select to authenticated using (exists (select 1 from public.customers c where c.id = customer_id and c.user_id = (select auth.uid())));

-- A clinic admin only sees records belonging to the clinic they administer.
create policy "clinic admins view appointments" on public.appointments for select to authenticated using (exists (select 1 from public.clinics c where c.id = clinic_id and c.admin_user_id = (select auth.uid())));
create policy "clinic admins update appointment status" on public.appointments for update to authenticated using (exists (select 1 from public.clinics c where c.id = clinic_id and c.admin_user_id = (select auth.uid()))) with check (exists (select 1 from public.clinics c where c.id = clinic_id and c.admin_user_id = (select auth.uid())));

insert into public.clinics (name, district, rating, description) values
  ('라이트 피부과', '강남구', 4.8, '피부과 전문의 상담과 자연스러운 안티에이징 시술'),
  ('루미에르 클리닉', '서초구', 4.7, '맞춤형 리프팅·피부결 관리 클리닉'),
  ('온유 메디컬', '송파구', 4.6, '여드름 흉터와 색소 케어 중심의 메디컬 에스테틱');

insert into public.services (clinic_id, name, category, price, duration, slots) values
  (1, '국산 보톡스', '보톡스', 89000, '20분', array['2026-09-05T11:00:00+09:00','2026-09-06T14:00:00+09:00','2026-09-08T16:00:00+09:00']),
  (1, '입술 필러 1cc', '필러', 290000, '40분', array['2026-09-05T15:00:00+09:00','2026-09-07T11:00:00+09:00','2026-09-09T13:00:00+09:00']),
  (2, '슈링크 유니버스 300샷', '리프팅', 390000, '45분', array['2026-09-06T10:30:00+09:00','2026-09-07T14:30:00+09:00','2026-09-10T12:00:00+09:00']),
  (2, '물광 스킨부스터', '스킨부스터', 220000, '40분', array['2026-09-05T13:00:00+09:00','2026-09-08T11:30:00+09:00','2026-09-10T16:30:00+09:00']),
  (3, '피코토닝', '레이저', 120000, '30분', array['2026-09-05T10:00:00+09:00','2026-09-06T16:00:00+09:00','2026-09-09T14:00:00+09:00']),
  (3, '여드름 흉터 프락셀', '레이저', 260000, '50분', array['2026-09-07T13:00:00+09:00','2026-09-08T15:00:00+09:00','2026-09-10T10:00:00+09:00']);
